language: csharp
dist: trusty
mono: latest
dotnet: 2.0.0

install:
- REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
- REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
- REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
- dotnet restore

script:
- dotnet build
- dotnet test Core.Shogi.Tests/Core.Shogi.Tests.csproj

after_success:
- cd Core.Shogi.Tests
- dotnet cover bin/Debug/netcoreapp2.0
- mono $HOME/.nuget/packages/coveralls.io/1.3.4/tools/coveralls.net.exe --opencover coverage.xml --r $COVERALLS_TOKEN -f
