copy Core.Shogi.Console\bin\Debug\netcoreapp1.1\*.pdb Core.Shogi.Tests\bin\Debug\netcoreapp1.1\

REM 

@call %USERPROFILE%\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"test Core.Shogi.Tests/Core.Shogi.Tests.csproj" -searchdirs:"Core.Shogi.Tests\bin\Debug\netcoreapp1.1" -output:coverage.xml -register:user -filter:"+[*]* -[*]AutoGeneratedProgram -[*]*Should" -oldStyle -returntargetcode

REM @call %USERPROFILE%\.nuget\packages\opencover\4.6.519\tools\OpenCover.Console.exe -target:"dotnet.exe" -targetargs:"Core.Shogi.Console\bin\Debug\netcoreapp1.1\Core.Shogi.Console.dll" -output:coverage.xml -register:user -coverbytest:"*"  -oldStyle