#!/usr/bin/env bash 

#hack to get opencover to work on mono due to ColoredConsoleAppender issue.
cp log4net.config $HOME/.nuget/packages/opencover/4.6.519/tools/log4net.config -f

mono $HOME/.nuget/packages/opencover/4.6.519/tools/OpenCover.Console.exe -target:"/usr/bin/dotnet" -targetargs:"test Core.Shogi.Tests/Core.Shogi.Tests.csproj" -output:coverage.xml -register:user -filter:"+[*]* -[*]AutoGeneratedProgram" -oldStyle -log:Off

tail coverage.xml

dotnet test Core.Shogi.Tests/Core.Shogi.Tests.csproj