#!/usr/bin/env bash 

#hack to get opencover to work on mono due to ColoredConsoleAppender issue.
cp log4net.config $HOME/.nuget/packages/opencover/4.6.519/tools/log4net.config -f

cp Core.Shogi.Console/bin/Debug/netcoreapp1.1/*.pdb Core.Shogi.Tests/bin/Debug/netcoreapp1.1/

mono $HOME/.nuget/packages/opencover/4.6.519/tools/OpenCover.Console.exe -target:"/usr/bin/dotnet" -targetargs:"test Core.Shogi.Tests/Core.Shogi.Tests.csproj" -output:coverage.xml -register:user -filter:"+[*]* -[*]AutoGeneratedProgram -[*]Should" -oldStyle -returntargetcode

tail coverage.xml

dotnet test Core.Shogi.Tests/Core.Shogi.Tests.csproj